

create table ACCOUNT (
ID BIGINT PRIMARY KEY, 
ACTIVE SMALLINT NOT NULL,
ANSWER VARCHAR(100) NOT NULL,
AUTHORIZED SMALLINT NOT NULL,
CREATED_AT TIMESTAMP,
LOGIN VARCHAR(20) NOT NULL, 
CONSTRAINT UNIQUE_LOGIN unique (LOGIN),
MODIFIED_AT TIMESTAMP,
"NAME" VARCHAR(60) NOT NULL,
PASSWORD VARCHAR(64) NOT NULL, 
PHONE_NUMBER VARCHAR(13) NOT NULL,
QUESTION VARCHAR(100) NOT NULL,
SURNAME	VARCHAR(100) NOT NULL,
VERSION	INTEGER NOT NULL,
LEVEL_OF_ACCESS	VARCHAR(31) NOT NULL,
ACCOUNT_CREATOR BIGINT,
CONSTRAINT CCUNTCCOUNTCREATOR FOREIGN KEY (ACCOUNT_CREATOR) REFERENCES ACCOUNT(ID),
MODIFIED_BY BIGINT,
CONSTRAINT ACCOUNTMODIFIED_BY FOREIGN KEY (MODIFIED_BY) REFERENCES ACCOUNT(ID)
);

-- ALTER TABLE
-- CONSTRAINT CCUNTCCOUNTCREATOR
-- FOREIGN KEY (ACCOUNT_CREATOR) REFERENCES ACCOUNT(ID);

create table SPECIALIZATION (
ID BIGINT PRIMARY KEY, 
SPECIALIZATION_NAME VARCHAR(100) NOT NULL,
SPECIALIZATION_CODE VARCHAR(3) NOT NULL,
CONSTRAINT UNIQUE_SPECIALIZA unique (SPECIALIZATION_CODE), 
SPECIALIZATION_CREATOR BIGINT,
CONSTRAINT SPCLZTNSPCLZTNCRTR FOREIGN KEY (SPECIALIZATION_CREATOR) REFERENCES ACCOUNT(ID),
MODIFIED_BY BIGINT,
CONSTRAINT SPCLIZATIONMDFEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES ACCOUNT(ID),
VERSION	INTEGER NOT NULL,
MODIFIED_AT TIMESTAMP,
CREATED_AT TIMESTAMP NOT NULL);

create table SPECIALIST (
ID BIGINT PRIMARY KEY, 
SPECIALIST_NAME VARCHAR(100) NOT NULL,
SPECIALIST_SURNAME VARCHAR(100) NOT NULL,
CREATED_AT TIMESTAMP NOT NULL,
LICENSE_NUMBER VARCHAR(7) NOT NULL,
CONSTRAINT UNIQUE_LICENSE_NR unique (LICENSE_NUMBER), 
SPECIALIZATION BIGINT,
CONSTRAINT SPCLISTSPCLIZATION FOREIGN KEY (SPECIALIZATION) REFERENCES SPECIALIZATION(ID),
VERSION	INTEGER NOT NULL,
SPECIALIST_CREATOR BIGINT,
CONSTRAINT SPCLSTSPCLSTCRATOR FOREIGN KEY (SPECIALIST_CREATOR) REFERENCES ACCOUNT(ID),
MODIFIED_BY BIGINT,
CONSTRAINT SPCIALISTMDIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES ACCOUNT(ID),
MODIFIED_AT TIMESTAMP,
ACTIVE SMALLINT NOT NULL);

create table RESERVATION (
ID BIGINT PRIMARY KEY, 
CREATED_AT TIMESTAMP NOT NULL,
MODIFIED_AT TIMESTAMP,
RESERVATION_DATE TIMESTAMP NOT NULL,
VERSION	INTEGER NOT NULL,
RESERVATION_CREATOR BIGINT,
CONSTRAINT RSRVTNRSRVTNCRATOR FOREIGN KEY (RESERVATION_CREATOR) REFERENCES ACCOUNT(ID),
RESERVED_SPECIALIST BIGINT,
CONSTRAINT RSRVTNRSRVDSPCLIST FOREIGN KEY (RESERVED_SPECIALIST) REFERENCES SPECIALIST(ID),
MODIFIED_BY BIGINT,
CONSTRAINT RSRVATIONMDIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES ACCOUNT(ID),
CONSTRAINT UNIQUE_SPECIAL_DATE unique (RESERVATION_DATE, RESERVED_SPECIALIST),
CONSTRAINT UNIQUE_CREATOR_DATE unique (RESERVATION_CREATOR, RESERVATION_DATE)
);

CREATE VIEW AUTH_TABLE AS 
SELECT LOGIN, PASSWORD, LEVEL_OF_ACCESS FROM ACCOUNT WHERE active>0 AND authorized>0 AND NOT level_of_access  = 'access.level.newaccount';



